[package]
name = "cellpress-unofficial"
version = "0.1.1"
entrypoint = "src/lib.typ"
authors = ["Robin Eklind"]
license = "0BSD"
description = "Unofficial Cell Press template for Typst."
repository = "https://github.com/mewmew/cellpress-unofficial"
categories = ["paper"]
disciplines = ["biology", "chemistry", "medicine"]
exclude = ["/example", "/inc/thumbnail.png"]

[template]
path = "template"
entrypoint = "report.typ"
thumbnail = "inc/thumbnail.png"
