[package]
name = "cellpress-unofficial"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Robin Eklind"]
license = "0BSD"
description = "Unofficial CELL press styles for Typst."
exclude = ["example", "inc"]
repository = "https://github.com/mewmew/cellpress-unofficial"
