[package]
name = "cellpress-unofficial"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Robin Eklind"]
license = "0BSD"
description = "Unofficial Cell Press styles for Typst."
repository = "https://github.com/mewmew/cellpress-unofficial"
exclude = ["/example"]
